/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dex.counter;

import info.persistent.dex.DexMethodCounts;
import java.util.NavigableMap;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author kasper
 */
public class resultForm extends javax.swing.JDialog {

    /**
     * Creates new form resultForm
     *
     * @param parent
     * @param modal
     */
    public resultForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void testMe() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private int overall;

    public void setNode(DexMethodCounts.Node packageTree) {
        overall = packageTree.getCount();
        String conclusion = " methods, which is ok";
        if (overall > 65536) {
            conclusion = " methods,WARNING MULTIDEX required!!! !!!!! ";
        } else if (overall > 60000) {
            conclusion = " methods,WARNING You are close to the limit! !!! ";
        }
        setTitle("overall : " + overall + conclusion);
        DefaultMutableTreeNode root = getNodesFromChild(packageTree, "Packages");
        TreeModel resultModel = new DefaultTreeModel(root);
        jTree1.setModel(resultModel);
    }

    private DefaultMutableTreeNode getNodesFromChild(DexMethodCounts.Node node, String title) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(title + " - " + node.getCount());

        NavigableMap<String, DexMethodCounts.Node> children = node.getChildren();
        children.navigableKeySet().stream().forEach((name) -> {
            DexMethodCounts.Node child = children.get(name);
            root.add(getNodesFromChild(child, name));
        });
        return root;
    }

}
